---
name: unit-tests
on: [push, pull_request]
jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        #os: [ ubuntu-latest, macos-latest ]
        #php-version: [ 5.3, 5.4, 5.5, 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0, 8.1, 8.2, 8.3 ]
        os: [ ubuntu-latest, macos-latest ]
        php-version: [ 7.4, 8.0, 8.1, 8.2, 8.3 ]
        exclude:
          - { os: macos-latest, php-version: 8.3 }
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: iconv
          tools: phpunit
      - name: Information
        run: |
          php --version
          phpunit --version
      - name: Compile
        run: |
          make all
      - name: Run unit tests
        run: |
          make test
